### ISSUE TITLE
Podcasts showing as "inactive" with no episodes

### ISSUE THREAD

**Issue by janjuafarooq** [ericmedina024/podcast-sponsor-block#4]
I followed all the steps and have my container running on Render. When I add the following podcasts, I see them as "inactive" with no errors within my app:

https://www.youtube.com/@ramitsethi/podcasts with playlist ID PLPZCUlZ2z01lvgC4lquCWOoVsCzTOxIqz
https://www.youtube.com/@TheVerge/podcasts for The Vergecast with playlist ID PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa

I was able to successfully add them in my Overcast app and it shows a different picture and metadata compared to the publicly available versions. Here are the logs:

127.0.0.1 - - [04/Apr/2024:12:55:47 +0000] "GET /rss/youtube/PLPZCUlZ2z01lvgC4lquCWOoVsCzTOxIqz HTTP/1.1" 200 204515 "-" "Overcast/1.0 Podcast Sync (0 subscribers; feed-id=0; +http://overcast.fm/)"
127.0.0.1 - - [04/Apr/2024:12:55:47 +0000] "HEAD / HTTP/1.1" 401 0 "-" "Go-http-client/1.1"
2024-04-04 12:55:47,591 [INFO] Generating RSS feed for YouTube playlist PLPZCUlZ2z01lvgC4lquCWOoVsCzTOxIqz
2024-04-04 12:55:47,715 [INFO] Grabbing episodes from YouTube playlist PLPZCUlZ2z01lvgC4lquCWOoVsCzTOxIqz
127.0.0.1 - - [04/Apr/2024:12:55:47 +0000] "GET /rss/youtube/PLPZCUlZ2z01lvgC4lquCWOoVsCzTOxIqz HTTP/1.1" 200 204515 "-" "Overcast/1.0 Podcast Sync (0 subscribers; feed-id=0; +http://overcast.fm/)"
2024-04-04 12:58:59,578 [INFO] Generating RSS feed for YouTube playlist PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa
2024-04-04 12:58:59,673 [INFO] Grabbing episodes from YouTube playlist PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa
127.0.0.1 - - [04/Apr/2024:12:59:00 +0000] "GET /rss/youtube/PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa HTTP/1.1" 200 236818 "-" "Overcast/1.0 Podcast Sync (0 subscribers; feed-id=0; +http://overcast.fm/)"
127.0.0.1 - - [04/Apr/2024:12:59:00 +0000] "GET /rss/youtube/PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa HTTP/1.1" 200 236818 "-" "Overcast/1.0 Podcast Sync (0 subscribers; feed-id=0; +http://overcast.fm/)"
127.0.0.1 - - [04/Apr/2024:12:59:36 +0000] "GET /rss/youtube/PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa HTTP/1.1" 401 0 "-" "Overcast/977 CFNetwork/1494.0.7 Darwin/23.4.0"
127.0.0.1 - - [04/Apr/2024:12:59:36 +0000] "GET /rss/youtube/PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa HTTP/1.1" 401 0 "-" "Overcast/977 CFNetwork/1494.0.7 Darwin/23.4.0"
127.0.0.1 - - [04/Apr/2024:12:59:37 +0000] "GET /rss/youtube/PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa HTTP/1.1" 401 0 "-" "Overcast/977 CFNetwork/1494.0.7 Darwin/23.4.0"
127.0.0.1 - - [04/Apr/2024:12:59:37 +0000] "GET /rss/youtube/PL39u5ZEfYDEO5PaNRWyqloGY6zzJ1fjBa HTTP/1.1" 200 236818 "-" "Overcast/1.0 Podcast Sync (0 subscribers; feed-id=0; +http://overcast.fm/)"

I tried the same thing with your instructions for the sleep with me podcast with the same results.

**Comment by janjuafarooq** [comment]
Ok slight update -

I updated my env var PODCAST_DATA_PATH=/tmp/podcastdata

and the docker command now includes this too:
docker run -it -v /tmp/podcastdata:/tmp/podcastdata --env-file example-configuration.env -p 8080:8080 podcast-sponsor-block

The episodes are listed, but I am now getting "Not Authorized" when I try to download them

**Comment by janjuafarooq** [comment]
And one more - it seems to work fine with Apple Podcasts, but not Overcast :( Not sure how to proceed further here.

**Comment by janjuafarooq** [comment]
Was able to get this resolved, this seems like an actual Overcast issue. Enabling the following flags works (you don't actually need to send the key via query param).

PODCAST_ALLOW_QUERY_PARAM_AUTH=true
PODCAST_APPEND_AUTH_PARAM_TO_RESOURCE_LINKS=true

**Comment by ericmedina024** [comment]
thank you for leaving the solution! it's good to know that overcast requires the use of that option.
